PokeAPi/PokeAPi/Models/Ability.cs
using Newtonsoft.Json;
using PokeAPi.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokeAPi.Models
{
    public class Ability
    {
        [JsonProperty("ability")]
        public Species AbilityAbility { get; set; }

        [JsonProperty("is_hidden")]
        public bool IsHidden { get; set; }

        [JsonProperty("slot")]
        public long Slot { get; set; }
    }
    public partial class Species
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class GameIndex
    {
        [JsonProperty("game_index")]
        public long GameIndexGameIndex { get; set; }

        [JsonProperty("version")]
        public Species Version { get; set; }
    }

    public partial class HeldItem
    {
        [JsonProperty("item")]
        public Species Item { get; set; }

        [JsonProperty("version_details")]
        public VersionDetail[] VersionDetails { get; set; }
    }

    public partial class VersionDetail
    {
        [JsonProperty("rarity")]
        public long Rarity { get; set; }

        [JsonProperty("version")]
        public Species Version { get; set; }
    }

    public partial class Move
    {
        [JsonProperty("move")]
        public Species MoveMove { get; set; }

        [JsonProperty("version_group_details")]
        public VersionGroupDetail[] VersionGroupDetails { get; set; }
    }

    public partial class VersionGroupDetail
    {
        [JsonProperty("level_learned_at")]
        public long LevelLearnedAt { get; set; }

        [JsonProperty("move_learn_method")]
        public Species MoveLearnMethod { get; set; }

        [JsonProperty("version_group")]
        public Species VersionGroup { get; set; }
    }

    public partial class Sprites
    {
        [JsonProperty("back_default")]
        public Uri BackDefault { get; set; }

        [JsonProperty("back_female")]
        public object BackFemale { get; set; }

        [JsonProperty("back_shiny")]
        public Uri BackShiny { get; set; }

        [JsonProperty("back_shiny_female")]
        public object BackShinyFemale { get; set; }

        [JsonProperty("front_default")]
        public Uri FrontDefault { get; set; }

        [JsonProperty("front_female")]
        public object FrontFemale { get; set; }

        [JsonProperty("front_shiny")]
        public Uri FrontShiny { get; set; }

        [JsonProperty("front_shiny_female")]
        public object FrontShinyFemale { get; set; }
    }

    public partial class Stat
    {
        [JsonProperty("base_stat")]
        public long BaseStat { get; set; }

        [JsonProperty("effort")]
        public long Effort { get; set; }

        [JsonProperty("stat")]
        public Species StatStat { get; set; }
    }

    public partial class TypeElement
    {
        [JsonProperty("slot")]
        public long Slot { get; set; }

        [JsonProperty("type")]
        public Species Type { get; set; }
    }
}

PokeAPi/PokeAPi/Models/GetPokemons.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokeAPi.Models
{
    public class GetPokemons
    {
        public virtual List<Result> PokemonesList { get; set; }
        public virtual List<PokemonDetail> PokemonDetailList { get; set; }
    }
}

PokeAPi/PokeAPi/Models/PokemonDetail.cs
using Newtonsoft.Json;
using PokeAPi.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokeAPi.Models
{
    public class PokemonDetail
    {
        [JsonProperty("abilities")]
        public Ability[] Abilities { get; set; }

        [JsonProperty("base_experience")]
        public long BaseExperience { get; set; }

        [JsonProperty("forms")]
        public Species[] Forms { get; set; }

        [JsonProperty("game_indices")]
        public GameIndex[] GameIndices { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("held_items")]
        public HeldItem[] HeldItems { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("is_default")]
        public bool IsDefault { get; set; }

        [JsonProperty("location_area_encounters")]
        public Uri LocationAreaEncounters { get; set; }

        [JsonProperty("moves")]
        public Move[] Moves { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("order")]
        public long Order { get; set; }

        [JsonProperty("species")]
        public Species Species { get; set; }

        [JsonProperty("sprites")]
        public Sprites Sprites { get; set; }

        [JsonProperty("stats")]
        public Stat[] Stats { get; set; }

        [JsonProperty("types")]
        public TypeElement[] Types { get; set; }

        [JsonProperty("weight")]
        public long Weight { get; set; }
    }
}

PokeAPi/PokeAPi/Models/Pokemones.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PokeAPi.Models
{
    public class Pokemones
    {
        [JsonProperty("results")]
        public Result[] Results { get; set; }
    }
    public partial class Result
    {
        [JsonProperty("name")]
        public string Name { get; set; }
        [JsonProperty("url")]
        public string Url { get; set; }

    }
}

PokeAPi/PokeAPi/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PokeAPi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

       

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PokeAPi/PokeAPi/Controllers/PokemonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using c = PokeAPi.Utilities;
using PokeAPi.Models;

namespace PokeAPi.Controllers
{
    public class PokemonController : Controller
    {
        // GET: Pokemon
        public ActionResult Index()
        {

            var client = new HttpClient();
            client.BaseAddress = new Uri("https://pokeapi.co/api/v2/pokemon/");
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var response = client.GetAsync("https://pokeapi.co/api/v2/pokemon/25").Result;
            var pokemonDetail = new PokemonDetail();
            var pokemones = new Pokemones();
            List<Result> nombre = new List<Result>();
            List<PokemonDetail> pokemonDetailList = new List<PokemonDetail>();  
            
            if (response.IsSuccessStatusCode)
            {

                response = client.GetAsync("https://pokeapi.co/api/v2/pokemon").Result;
                var result = response.Content.ReadAsStringAsync().Result;
                pokemones = JsonConvert.DeserializeObject<Pokemones>(result);
                foreach (var pokemon in pokemones.Results)
                {
                    nombre.Add(pokemon);
                    //invocar de nuevo el api con la url del pokemon
                     response = client.GetAsync(pokemon.Url).Result;
                    //validar si la respuesta fue satisfactoria
                    if (response.IsSuccessStatusCode)
                    {
                        //deserealizar 
                        result = response.Content.ReadAsStringAsync().Result;
                        pokemonDetail = JsonConvert.DeserializeObject<PokemonDetail>(result);
                        pokemonDetailList.Add(pokemonDetail);
                    }                    
                    //agregar ala lista

                }

                //var result = response.Content.ReadAsStringAsync().Result;
                //pokemondetail = JsonConvert.DeserializeObject<PokemonDetail>(result);
            }

            var pokemonesL = new GetPokemons();
            pokemonesL = new GetPokemons { PokemonesList = nombre, PokemonDetailList = pokemonDetailList };            
            return View (pokemonesL);
        }
        public ActionResult Hello()
        {
            return PartialView ();
        }
    }
   

    

    
}

PokeAPi/PokeAPi/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PokeAPi/PokeAPi/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Universidad Tecnologica de Hermosillo </h3>
                
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            @*<div class="col-md-6 col-lg-12">*@
            <div class="col-md-12">
                <div class="card card-body">
                    <div class="portlet light portlet-fit add-padding-pagination">
                        <div class="portlet-title" style="padding-bottom: 0px;">

                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="card">
                                    <img src="https://cdn.vox-cdn.com/thumbor/SCHYwQY8eqWYGzLZ0rUi50xP7V0=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22331126/Pokemon_Legends_Arceus_screenshot_17.jpg" alt="Imagen" />


                                </div>
                            </div>
                          
                        </div>
                    </div>

                </div>

            </div>
        </div>



        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer"> © 2021 Interfases y Sistemas Electrónicos S.A.P.I. de C.V. intertel.mx</footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>


</div>

PokeAPi/PokeAPi/Views/Pokemon/Hello.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-wrapper">
    
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Departamentos</h3>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                </ol>
            </div>           
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            @*<div class="col-md-6 col-lg-12">*@
            <div class="col-md-12">
                <div class="card card-body">
                    <div class="portlet light portlet-fit add-padding-pagination">
                        <div class="portlet-title" style="padding-bottom: 0px;">
                        
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="card">
                                    <img class="card-img-top" src="../../Content/assets/images/background/profile-bg.jpg" alt="Card image cap">
                                    <div class="card-body little-profile text-center">
                                        <div class="pro-img"><img src="../../Content/assets/images/users/4.jpg" alt="user" /></div>
                                        <h3 class="m-b-0">Angela Dominic</h3>
                                        <p>Web Designer &amp; Developer</p>
                                        <a href="javascript:void(0)" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded">Follow</a>
                                        <div class="row text-center m-t-20">
                                            <div class="col-lg-4 col-md-4 m-t-20">
                                                <h3 class="m-b-0 font-light">1099</h3><small>Articles</small>
                                            </div>
                                            <div class="col-lg-4 col-md-4 m-t-20">
                                                <h3 class="m-b-0 font-light">23,469</h3><small>Followers</small>
                                            </div>
                                            <div class="col-lg-4 col-md-4 m-t-20">
                                                <h3 class="m-b-0 font-light">6035</h3><small>Following</small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="card">
                                    <img class="card-img-top" src="../../Content/assets/images/background/profile-bg.jpg" alt="Card image cap">
                                    <div class="card-body little-profile text-center">
                                        <div class="pro-img"><img src="../../Content/assets/images/users/4.jpg" alt="user" /></div>
                                        <h3 class="m-b-0">Angela Dominic</h3>
                                        <p>Web Designer &amp; Developer</p>
                                        <a href="javascript:void(0)" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded">Follow</a>
                                        <div class="row text-center m-t-20">
                                            <div class="col-lg-4 col-md-4 m-t-20">
                                                <h3 class="m-b-0 font-light">1099</h3><small>Articles</small>
                                            </div>
                                            <div class="col-lg-4 col-md-4 m-t-20">
                                                <h3 class="m-b-0 font-light">23,469</h3><small>Followers</small>
                                            </div>
                                            <div class="col-lg-4 col-md-4 m-t-20">
                                                <h3 class="m-b-0 font-light">6035</h3><small>Following</small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                        
                    </div>

                </div>
        </div>



        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer"> © 2021 Interfases y Sistemas Electrónicos S.A.P.I. de C.V. intertel.mx</footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>


</div>

PokeAPi/PokeAPi/Views/Pokemon/Index.cshtml
@model PokeAPi.Models.GetPokemons
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}






<div class="page-wrapper">

    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Pokemones</h3>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li class="breadcrumb-item active"><a href="@Url.Action("Index", "Pokemon")">Dashboard</a></li>
                </ol>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            @*<div class="col-md-6 col-lg-12">*@
            <div class="col-md-12">
                <div class="card card-body">
                    <div class="portlet light portlet-fit add-padding-pagination">
                        <div class="portlet-title" style="padding-bottom: 0px;">
                            <div class="caption bold uppercase font-green-seagreen ">
                                <i class="font-green-seagreen  bold icon-list"></i>
                                <span class="caption-subject bold">Listado de Pokemones</span>
                            </div>
                        </div>
                        <div class="row">
                            @if (Model != null && Model.PokemonDetailList.Count() > 0)
                            {
                                foreach (var item in Model.PokemonDetailList)
                                {                                   
                                    <div class="col-sm-4">
                                        <div class="card">
                                            <img class="card-img-top" src="https://comicvine.gamespot.com/a/uploads/original/11138/111384217/6920066-d5ywg9l-b4a8a6e1-06a0-4c22-8dc6-8605193a1e7b.jpg" alt="Card image cap">
                                            <div class="card-body little-profile text-center">
                                                <div class="pro-img"><img src="@item.Sprites.FrontDefault" alt="user" /></div>
                                                <h3 class="m-b-0">@item.Name</h3>
                                                <p>Experiencia acumulada: @item.BaseExperience</p>
                                                <a href="javascript:void(0)" class="m-t-10 waves-effect waves-dark btn btn-primary btn-md btn-rounded">Detalles</a>
                                                <div class="row text-center m-t-20">
                                                    <div class="col-lg-4 col-md-4 m-t-20">
                                                        <h3 class="m-b-0 font-light">@item.Stats[0].BaseStat</h3><small>Vida</small>
                                                    </div>
                                                    <div class="col-lg-4 col-md-4 m-t-20">
                                                        <h3 class="m-b-0 font-light">@item.Stats[1].BaseStat</h3><small>Ataque</small>
                                                    </div>
                                                    <div class="col-lg-4 col-md-4 m-t-20">
                                                        <h3 class="m-b-0 font-light">@item.Stats[2].BaseStat</h3><small>Defensa</small>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }

                            @*<div class="col-sm-3">
                                asdsad
                            </div>*@
                        </div>                      
       
                        
                    </div>
                </div>
            </div>


        </div>



        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer"> © 2023 Marin Moreno Jesus Paul</footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>


</div>